export const ROUTES = {
  auth: "/auth",
  login: "login",
  signup: 'signup',
  documents: "/documents",
  messages: "/messages",
  invoices: "/invoices",
  customer_review: "/customer-review",
  suppliers: "/suppliers",
  payment: "/payment",
  approval: "/approval",
  posting: "/posting",
  reports: "/reports",
  team: "/team",
  settings: "/settings",
}