export * from './DocumentsPage/DocumentPage';
export * from './DashboardPage/DashboardPage';
export * from './MessagesPage/MessagesPage';
export * from './InvoicesPage/InvoicePage';
export * from './LoginPage/LoginPage';
export * from './SignupPage/SignupPage';
export * from './TeamPage/TeamPage';
export * from './ProfileSettingPage/ProfileSettingPage';
export * from './GoogleLoginDataPage/GoogleLoginDataPage';
